### ISSUE TITLE
WillowMeCreations is one word.

### ISSUE THREAD

**Issue by willowmecreations** [ampersandcastles/willowmecreationsV2#1]
Title.

Pretty self explanatory. Several instances of it being made into three separate words. Do better!

**Comment by ampersandcastles** [comment]
I'm so sorry. I just corrected this issue in the latest [commit](https://github.com/ampersandcastles/willowmecreationsV2/commit/e31fbb263191adb3f282b4d1676b69a18245a9f0). Thank you for your patience.
